name: test
on:
  push:
    branches:
      - "*"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        nacos:
          - "v2.1.2"
          - "v2.2.3"
          - "v2.3.2"
          - "v2.4.3"
          - "v2.5.1"
          - "v3.1.0"
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Set up nacos info
        run: |
          if [[ "${NACOS_VERSION}" =~ ^v3 ]]; then
            cat >> $GITHUB_ENV <<EOF
          NACOS_HOST=http://127.0.0.1:8080
          NACOS_STATE=http://127.0.0.1:8080/v3/console/server/state
          NACOS_AUTH_URL=http://127.0.0.1:8080/v3/auth/user/admin
          NACOS_USERNAME=nacos
          NACOS_PASSWORD=nacos
          EOF
          else
            cat >> $GITHUB_ENV <<EOF
          NACOS_HOST=http://127.0.0.1:8848/nacos
          NACOS_STATE=http://127.0.0.1:8848/nacos/v1/console/server/state
          NACOS_AUTH_URL=http://127.0.0.1:8848/nacos/v1/auth/users/admin
          NACOS_USERNAME=nacos
          NACOS_PASSWORD=nacos
          EOF
          fi
        env:
          NACOS_VERSION: ${{ matrix.nacos }}

      - name: Setup Nacos
        run: |
          docker compose up -d
          retries=100
          while [ $retries -gt 0 ]; do
            curl -sf "${NACOS_STATE}" && break
            echo "Waiting for Nacos to be ready..."
            retries=$((retries-1))
            sleep 1
          done
          if [ $retries -eq 0 ]; then
            echo "nacos start failed"
            exit 1
          fi
          if [[ ! "${NACOS_VERSION}" =~ ^v2\.[123]\.* ]]; then
            curl -sf -XPOST "${NACOS_AUTH_URL}" -d "password=$NACOS_PASSWORD"
          fi
        env:
          NACOS_VERSION: ${{ matrix.nacos }}

      - run: go mod download
      - env:
          ACC: "true"
        run: make test
        timeout-minutes: 10

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
